In [5]:
import numpy as np
arr=np.array([10,20,30,40,50])
print("Nump array")
print(arr)


Nump array
[10 20 30 40 50]


In [11]:
arr[0:3]

array([10, 20, 30])

In [12]:
arr[-3:-1]

array([30, 40])

In [17]:
print("Addition:",arr+3)

Addition: [13 23 33 43 53]


In [18]:
print("Substraction:",arr-3)

Substraction: [ 7 17 27 37 47]


In [19]:
print("multiplication:",arr*5)

multiplication: [ 50 100 150 200 250]


In [20]:
print("Divisio:",arr/5)

Divisio: [ 2.  4.  6.  8. 10.]


In [28]:
print("Array:",arr)
Reshape=arr.reshape(5,1)
print(Reshape)

Array: [10 20 30 40 50]
[[10]
 [20]
 [30]
 [40]
 [50]]


In [30]:
print("Array:",arr)
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Max:",np.max(arr))



Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Max: 50


In [48]:
import pandas as pd
data = {
    "name": ["Asha", "Ravi", "Meera", "Karan"],
    "marks":[88,72,91,65],
    "branch": ["CSF", "ECE", "CSE", "ISF"]
}
df = pd.DataFrame(data)
print(df)


    name  marks branch
0   Asha     88    CSF
1   Ravi     72    ECE
2  Meera     91    CSE
3  Karan     65    ISF


In [52]:
print(df["name"])
print(df["marks"])

0     Asha
1     Ravi
2    Meera
3    Karan
Name: name, dtype: str
0    88
1    72
2    91
3    65
Name: marks, dtype: int64


In [53]:
print(df.iloc[0])

name      Asha
marks       88
branch     CSF
Name: 0, dtype: object


In [54]:
print(df.iloc[3])

name      Karan
marks        65
branch      ISF
Name: 3, dtype: object


In [59]:
a=len(data)
for i in range (a):
 print(df.iloc[i])

name      Asha
marks       88
branch     CSF
Name: 0, dtype: object
name      Ravi
marks       72
branch     ECE
Name: 1, dtype: object
name      Meera
marks        91
branch      CSE
Name: 2, dtype: object


In [62]:

    print("*")

*


In [1]:

a='* '
for i in range(-6,0):
    print(i*a)